"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptorganizationinviteresponse import (
    AcceptOrganizationInviteResponse,
    AcceptOrganizationInviteResponseTypedDict,
)
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AcceptOrganizationInviteAcceptOrganizationInviteRequestTypedDict(TypedDict):
    r"""AcceptOrganizationInviteRequest contains the invitation to accept."""

    token: str
    r"""The invitation token from the email link."""


class AcceptOrganizationInviteAcceptOrganizationInviteRequest(BaseModel):
    r"""AcceptOrganizationInviteRequest contains the invitation to accept."""

    token: str
    r"""The invitation token from the email link."""


class AcceptOrganizationInviteRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization the invitation belongs to.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """
    invite_id: str
    r"""Invitation ID to accept.
    Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
    """
    body: AcceptOrganizationInviteAcceptOrganizationInviteRequestTypedDict


class AcceptOrganizationInviteRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Organization the invitation belongs to.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """

    invite_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Invitation ID to accept.
    Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
    """

    body: Annotated[
        AcceptOrganizationInviteAcceptOrganizationInviteRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AcceptOrganizationInviteResponseResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    headers: Dict[str, List[str]]
    accept_organization_invite_response: NotRequired[
        AcceptOrganizationInviteResponseTypedDict
    ]
    r"""Success"""


class AcceptOrganizationInviteResponseResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    headers: Dict[str, List[str]]

    accept_organization_invite_response: Optional[AcceptOrganizationInviteResponse] = (
        None
    )
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AcceptOrganizationInviteResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
