"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationmember import OrganizationMember, OrganizationMemberTypedDict
from factify.types import BaseModel
from typing_extensions import TypedDict


class AddOrganizationMemberResponseTypedDict(TypedDict):
    r"""AddOrganizationMemberResponse contains the added member."""

    member: OrganizationMemberTypedDict
    r"""OrganizationMember represents a member of an organization."""


class AddOrganizationMemberResponse(BaseModel):
    r"""AddOrganizationMemberResponse contains the added member."""

    member: OrganizationMember
    r"""OrganizationMember represents a member of an organization."""
