"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connect_error_details_any import (
    ConnectErrorDetailsAny,
    ConnectErrorDetailsAnyTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


ConnectErrorCode = Literal[
    "canceled",
    "unknown",
    "invalid_argument",
    "deadline_exceeded",
    "not_found",
    "already_exists",
    "permission_denied",
    "resource_exhausted",
    "failed_precondition",
    "aborted",
    "out_of_range",
    "unimplemented",
    "internal",
    "unavailable",
    "data_loss",
    "unauthenticated",
]
r"""The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code]."""


class ConnectErrorTypedDict(TypedDict):
    r"""Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation"""

    code: NotRequired[ConnectErrorCode]
    r"""The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code]."""
    details: NotRequired[List[ConnectErrorDetailsAnyTypedDict]]
    r"""A list of messages that carry the error details. There is no limit on the number of messages."""
    message: NotRequired[str]
    r"""A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client."""


class ConnectError(BaseModel):
    r"""Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    code: Optional[ConnectErrorCode] = None
    r"""The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code]."""

    details: Optional[List[ConnectErrorDetailsAny]] = None
    r"""A list of messages that carry the error details. There is no limit on the number of messages."""

    message: Optional[str] = None
    r"""A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "details", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m
