"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_createversionrequest import (
    FactifyAPIV1betaCreateVersionRequest,
    FactifyAPIV1betaCreateVersionRequestTypedDict,
)
from factify.types import BaseModel
from factify.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class CreateDocumentVersionRequestTypedDict(TypedDict):
    document_id_param: str
    r"""Document ID to create version for.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """
    body: FactifyAPIV1betaCreateVersionRequestTypedDict


class CreateDocumentVersionRequest(BaseModel):
    document_id_param: Annotated[
        str,
        pydantic.Field(alias="document_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Document ID to create version for.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """

    body: Annotated[
        FactifyAPIV1betaCreateVersionRequest,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]
