"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdocumentresponse import (
    CreateDocumentResponse,
    CreateDocumentResponseTypedDict,
)
from factify.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class CreateDocumentResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CreateDocumentResponseTypedDict


class CreateDocumentResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CreateDocumentResponse
