"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deleteapikeyquotaresponse import (
    DeleteAPIKeyQuotaResponse,
    DeleteAPIKeyQuotaResponseTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteAPIKeyQuotaRequestTypedDict(TypedDict):
    api_key_id: str
    r"""The API key ID (required)."""
    organization_id: NotRequired[str]
    r"""Optional: organization ID. If not provided, uses the caller's organization."""


class DeleteAPIKeyQuotaRequest(BaseModel):
    api_key_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The API key ID (required)."""

    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional: organization ID. If not provided, uses the caller's organization."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteAPIKeyQuotaResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: DeleteAPIKeyQuotaResponseTypedDict


class DeleteAPIKeyQuotaResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: DeleteAPIKeyQuotaResponse
