"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel
from typing_extensions import TypedDict


class DeleteOrganizationQuotaResponseTypedDict(TypedDict):
    r"""DeleteOrganizationQuotaResponse confirms deletion. Empty response - success indicated by no error."""


class DeleteOrganizationQuotaResponse(BaseModel):
    r"""DeleteOrganizationQuotaResponse confirms deletion. Empty response - success indicated by no error."""
