"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_documentlayout import (
    QcrV1alphaDocumentLayout,
    QcrV1alphaDocumentLayoutTypedDict,
)
from .qcr_v1alpha_documentrecord import (
    QcrV1alphaDocumentRecord,
    QcrV1alphaDocumentRecordTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DocumentBundleTypedDict(TypedDict):
    r"""DocumentBundle groups a document record with its optional spatial layout."""

    layout: NotRequired[QcrV1alphaDocumentLayoutTypedDict]
    r"""Top-level layout structure, joined to a DocumentRecord by record_id.
    Used with the Block-based record representation (DocumentRecord.blocks).
    """
    record: NotRequired[QcrV1alphaDocumentRecordTypedDict]
    r"""DocumentRecord is the QCR representation of an ingested document.
    Immutable once extracted. Source-format-agnostic.

    Structure is a flat sequence of blocks. Sections provide optional grouping
    and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
    — they do not contain other blocks. This constrains nesting to only what is
    semantically valid and gives every element a natural positional address.

    Addressing convention: every element is addressable by its index path through
    the typed containment hierarchy. Examples:
    blocks[2]                        → third block
    blocks[2].section.blocks[0]      → first block inside a section
    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
    blocks[3].list.items[2]          → third item of a list

    These addresses are deterministic for a given record and are used by
    DocumentLayout to join layout data to semantic content.
    """


class DocumentBundle(BaseModel):
    r"""DocumentBundle groups a document record with its optional spatial layout."""

    layout: Optional[QcrV1alphaDocumentLayout] = None
    r"""Top-level layout structure, joined to a DocumentRecord by record_id.
    Used with the Block-based record representation (DocumentRecord.blocks).
    """

    record: Optional[QcrV1alphaDocumentRecord] = None
    r"""DocumentRecord is the QCR representation of an ingested document.
    Immutable once extracted. Source-format-agnostic.

    Structure is a flat sequence of blocks. Sections provide optional grouping
    and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
    — they do not contain other blocks. This constrains nesting to only what is
    semantically valid and gives every element a natural positional address.

    Addressing convention: every element is addressable by its index path through
    the typed containment hierarchy. Examples:
    blocks[2]                        → third block
    blocks[2].section.blocks[0]      → first block inside a section
    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
    blocks[3].list.items[2]          → third item of a list

    These addresses are deterministic for a given record and are used by
    DocumentLayout to join layout data to semantic content.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["layout", "record"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
