"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accesslevel import AccessLevel
from .processingstatus import ProcessingStatus
from .subject import Subject, SubjectTypedDict
from .versionref import VersionRef, VersionRefTypedDict
from datetime import datetime
from factify.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DocumentTypedDict(TypedDict):
    r"""Document represents a Factify document."""

    access_level: AccessLevel
    created_at: datetime
    r"""Timestamp when document was created."""
    created_by: SubjectTypedDict
    r"""Subject is a lightweight reference to either a user or a bot.
    Used in embedded fields like created_by.
    For full details, call GetUser or GetBot with the subject's id.
    subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)

    """
    id: str
    r"""Unique ID for the document.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """
    processing_status: ProcessingStatus
    title: str
    r"""Document title."""
    url: str
    r"""URL for accessing the document on Factify."""
    current_version: NotRequired[VersionRefTypedDict]
    r"""VersionRef is a lightweight reference to a version."""
    description: NotRequired[Nullable[str]]
    r"""Optional document description."""


class Document(BaseModel):
    r"""Document represents a Factify document."""

    access_level: AccessLevel

    created_at: datetime
    r"""Timestamp when document was created."""

    created_by: Subject
    r"""Subject is a lightweight reference to either a user or a bot.
    Used in embedded fields like created_by.
    For full details, call GetUser or GetBot with the subject's id.
    subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)

    """

    id: str
    r"""Unique ID for the document.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """

    processing_status: ProcessingStatus

    title: str
    r"""Document title."""

    url: str
    r"""URL for accessing the document on Factify."""

    current_version: Optional[VersionRef] = None
    r"""VersionRef is a lightweight reference to a version."""

    description: OptionalNullable[str] = UNSET
    r"""Optional document description."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["current_version", "description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
