"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_organizationinvite import (
    FactifyAPIV1betaOrganizationInvite,
    FactifyAPIV1betaOrganizationInviteTypedDict,
)
from .factify_api_v1beta_pagination import (
    FactifyAPIV1betaPagination,
    FactifyAPIV1betaPaginationTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FactifyAPIV1betaListOrganizationInvitesResponseTypedDict(TypedDict):
    r"""ListOrganizationInvitesResponse contains a page of invitations."""

    pagination: FactifyAPIV1betaPaginationTypedDict
    r"""Pagination contains cursor-based pagination metadata.
    Follows Google AIP-158 for pagination field naming.
    """
    items: NotRequired[List[FactifyAPIV1betaOrganizationInviteTypedDict]]
    r"""List of invitations."""


class FactifyAPIV1betaListOrganizationInvitesResponse(BaseModel):
    r"""ListOrganizationInvitesResponse contains a page of invitations."""

    pagination: FactifyAPIV1betaPagination
    r"""Pagination contains cursor-based pagination metadata.
    Follows Google AIP-158 for pagination field naming.
    """

    items: Optional[List[FactifyAPIV1betaOrganizationInvite]] = None
    r"""List of invitations."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
