"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from factify.utils import FieldMetadata, MultipartFormMetadata
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class FactifyAPIV1betaCreateVersionRequestPayloadTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class FactifyAPIV1betaCreateVersionRequestPayload(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FactifyAPIV1betaCreateVersionRequestTypedDict(TypedDict):
    r"""CreateVersionRequest contains the file and metadata for creating a version."""

    payload: FactifyAPIV1betaCreateVersionRequestPayloadTypedDict
    r"""PDF file for new version"""
    document_id: NotRequired[str]
    r"""Document ID to create version for.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """
    title: NotRequired[Nullable[str]]
    r"""Optional version title."""
    description: NotRequired[Nullable[str]]
    r"""Description of changes in this version."""


class FactifyAPIV1betaCreateVersionRequest(BaseModel):
    r"""CreateVersionRequest contains the file and metadata for creating a version."""

    payload: Annotated[
        FactifyAPIV1betaCreateVersionRequestPayload,
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ]
    r"""PDF file for new version"""

    document_id: Annotated[Optional[str], FieldMetadata(multipart=True)] = None
    r"""Document ID to create version for.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """

    title: Annotated[OptionalNullable[str], FieldMetadata(multipart=True)] = UNSET
    r"""Optional version title."""

    description: Annotated[OptionalNullable[str], FieldMetadata(multipart=True)] = UNSET
    r"""Description of changes in this version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document_id", "title", "description"])
        nullable_fields = set(["title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
