"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_organization import (
    FactifyAPIV1betaOrganization,
    FactifyAPIV1betaOrganizationTypedDict,
)
from factify.types import BaseModel
from typing_extensions import TypedDict


class FactifyAPIV1betaAcceptOrganizationInviteResponseTypedDict(TypedDict):
    r"""AcceptOrganizationInviteResponse contains the organization the user joined."""

    organization: FactifyAPIV1betaOrganizationTypedDict
    r"""Organization represents a Factify organization."""


class FactifyAPIV1betaAcceptOrganizationInviteResponse(BaseModel):
    r"""AcceptOrganizationInviteResponse contains the organization the user joined."""

    organization: FactifyAPIV1betaOrganization
    r"""Organization represents a Factify organization."""
