"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_document import (
    FactifyAPIV1betaDocument,
    FactifyAPIV1betaDocumentTypedDict,
)
from factify.types import BaseModel
from typing_extensions import TypedDict


class FactifyAPIV1betaCreateDocumentResponseTypedDict(TypedDict):
    r"""CreateDocumentResponse contains the newly created document."""

    document: FactifyAPIV1betaDocumentTypedDict
    r"""Document represents a Factify document."""


class FactifyAPIV1betaCreateDocumentResponse(BaseModel):
    r"""CreateDocumentResponse contains the newly created document."""

    document: FactifyAPIV1betaDocument
    r"""Document represents a Factify document."""
