"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_organizationinvite import (
    FactifyAPIV1betaOrganizationInvite,
    FactifyAPIV1betaOrganizationInviteTypedDict,
)
from factify.types import BaseModel
from typing_extensions import TypedDict


class FactifyAPIV1betaResendOrganizationInviteResponseTypedDict(TypedDict):
    r"""ResendOrganizationInviteResponse contains the updated invitation."""

    invite: FactifyAPIV1betaOrganizationInviteTypedDict
    r"""OrganizationInvite represents an invitation to join an organization.
    accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset

    """


class FactifyAPIV1betaResendOrganizationInviteResponse(BaseModel):
    r"""ResendOrganizationInviteResponse contains the updated invitation."""

    invite: FactifyAPIV1betaOrganizationInvite
    r"""OrganizationInvite represents an invitation to join an organization.
    accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset

    """
