"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_apikey import (
    FactifyAPIV1betaAPIKey,
    FactifyAPIV1betaAPIKeyTypedDict,
)
from factify.types import BaseModel
from typing_extensions import TypedDict


class FactifyAPIV1betaRevokeAPIKeyResponseTypedDict(TypedDict):
    r"""RevokeApiKeyResponse contains the revoked API key."""

    api_key: FactifyAPIV1betaAPIKeyTypedDict
    r"""ApiKey represents an authentication credential for programmatic API access."""


class FactifyAPIV1betaRevokeAPIKeyResponse(BaseModel):
    r"""RevokeApiKeyResponse contains the revoked API key."""

    api_key: FactifyAPIV1betaAPIKey
    r"""ApiKey represents an authentication credential for programmatic API access."""
