"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getdocumentresponse import GetDocumentResponse, GetDocumentResponseTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDocumentRequestTypedDict(TypedDict):
    document_id: str
    r"""Document ID.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """


class GetDocumentRequest(BaseModel):
    document_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Document ID.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """


class GetDocumentResponseResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    headers: Dict[str, List[str]]
    get_document_response: NotRequired[GetDocumentResponseTypedDict]
    r"""Success"""


class GetDocumentResponseResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    headers: Dict[str, List[str]]

    get_document_response: Optional[GetDocumentResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["GetDocumentResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
