"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organization import Organization, OrganizationTypedDict
from .user import User, UserTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetMeResponseTypedDict(TypedDict):
    r"""GetMeResponse contains the authenticated user's profile."""

    user: UserTypedDict
    r"""User represents a human user account.
    Returned by GetUser (endpoint deferred).
    """
    organizations: NotRequired[List[OrganizationTypedDict]]
    r"""Organizations the user is a member of."""


class GetMeResponse(BaseModel):
    r"""GetMeResponse contains the authenticated user's profile."""

    user: User
    r"""User represents a human user account.
    Returned by GetUser (endpoint deferred).
    """

    organizations: Optional[List[Organization]] = None
    r"""Organizations the user is a member of."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organizations"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
