"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getorganizationresponse import (
    GetOrganizationResponse,
    GetOrganizationResponseTypedDict,
)
from factify.types import BaseModel
from factify.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetOrganizationRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization ID.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """


class GetOrganizationRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Organization ID.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """


class GetOrganizationResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetOrganizationResponseTypedDict


class GetOrganizationResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetOrganizationResponse
