"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getrecordresponse import GetRecordResponse, GetRecordResponseTypedDict
from factify.types import BaseModel
from factify.utils import FieldMetadata, QueryParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetRecordRequestTypedDict(TypedDict):
    version_id: str
    r"""Version ID to retrieve the record for.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """


class GetRecordRequest(BaseModel):
    version_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Version ID to retrieve the record for.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """


class GetRecordResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetRecordResponseTypedDict


class GetRecordResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetRecordResponse
