"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getrecordresponse import GetRecordResponse, GetRecordResponseTypedDict
from factify.types import BaseModel
from factify.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetVersionRecordRequestTypedDict(TypedDict):
    version_id: str
    r"""Version ID to retrieve the record for.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """


class GetVersionRecordRequest(BaseModel):
    version_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Version ID to retrieve the record for.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """


class GetVersionRecordResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetRecordResponseTypedDict


class GetVersionRecordResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetRecordResponse
