"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .documentpermissionset import DocumentPermissionSet, DocumentPermissionSetTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InspectAccessResponseTypedDict(TypedDict):
    r"""InspectAccessResponse contains the caller's permissions."""

    document_id: NotRequired[str]
    r"""Document ID."""
    permission_set: NotRequired[DocumentPermissionSetTypedDict]
    r"""DocumentPermissionSet contains the permissions the authenticated user has on a document."""


class InspectAccessResponse(BaseModel):
    r"""InspectAccessResponse contains the caller's permissions."""

    document_id: Optional[str] = None
    r"""Document ID."""

    permission_set: Optional[DocumentPermissionSet] = None
    r"""DocumentPermissionSet contains the permissions the authenticated user has on a document."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["document_id", "permission_set"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
