"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accessrequest import AccessRequest, AccessRequestTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListAccessRequestsResponseTypedDict(TypedDict):
    r"""ListAccessRequestsResponse contains the list of access requests."""

    has_more: NotRequired[bool]
    items: NotRequired[List[AccessRequestTypedDict]]


class ListAccessRequestsResponse(BaseModel):
    r"""ListAccessRequestsResponse contains the list of access requests."""

    has_more: Optional[bool] = None

    items: Optional[List[AccessRequest]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["has_more", "items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
