"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .listdocumentsresponse import ListDocumentsResponse, ListDocumentsResponseTypedDict
from datetime import datetime
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


ListDocumentsAccessLevel = Literal[
    "private",
    "organization",
    "public",
]
r"""Access level"""


ListDocumentsProcessingStatus = Literal[
    "processing",
    "ready",
    "failed",
]
r"""Processing status"""


class ListDocumentsRequestTypedDict(TypedDict):
    page_token: NotRequired[str]
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """
    page_size: NotRequired[int]
    r"""Maximum number of items to return per page (1-100). Default: 50."""
    created_by_id: NotRequired[List[str]]
    r"""Filter by creator ID(s). Returns documents matching ANY of the specified IDs."""
    access_level: NotRequired[List[ListDocumentsAccessLevel]]
    r"""Filter by access level(s). Returns documents matching ANY of the specified levels."""
    processing_status: NotRequired[List[ListDocumentsProcessingStatus]]
    r"""Filter by processing status(es). Returns documents matching ANY of the specified statuses."""
    created_after: NotRequired[datetime]
    r"""Filter by created.after (RFC 3339 format, e.g., 2024-01-15T09:30:00Z)"""


class ListDocumentsRequest(BaseModel):
    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return per page (1-100). Default: 50."""

    created_by_id: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by creator ID(s). Returns documents matching ANY of the specified IDs."""

    access_level: Annotated[
        Optional[List[ListDocumentsAccessLevel]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by access level(s). Returns documents matching ANY of the specified levels."""

    processing_status: Annotated[
        Optional[List[ListDocumentsProcessingStatus]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by processing status(es). Returns documents matching ANY of the specified statuses."""

    created_after: Annotated[
        Optional[datetime],
        pydantic.Field(alias="created.after"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by created.after (RFC 3339 format, e.g., 2024-01-15T09:30:00Z)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "page_token",
                "page_size",
                "created_by_id",
                "access_level",
                "processing_status",
                "created.after",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListDocumentsResponseResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    headers: Dict[str, List[str]]
    list_documents_response: NotRequired[ListDocumentsResponseTypedDict]
    r"""Success"""


class ListDocumentsResponseResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListDocumentsResponseResponse]],
        Callable[[], Awaitable[Optional[ListDocumentsResponseResponse]]],
    ]

    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    headers: Dict[str, List[str]]

    list_documents_response: Optional[ListDocumentsResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ListDocumentsResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
