"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .listdocumentpoliciesresponse import (
    ListDocumentPoliciesResponse,
    ListDocumentPoliciesResponseTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ListDocumentPoliciesRequestTypedDict(TypedDict):
    document_id: str
    r"""Document ID.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """
    page_token: NotRequired[str]
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """
    page_size: NotRequired[int]
    r"""Maximum number of items to return per page (1-100). Default: 50."""


class ListDocumentPoliciesRequest(BaseModel):
    document_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Document ID.
    Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
    """

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return per page (1-100). Default: 50."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page_token", "page_size"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListDocumentPoliciesResponseResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    headers: Dict[str, List[str]]
    list_document_policies_response: NotRequired[ListDocumentPoliciesResponseTypedDict]
    r"""Success"""


class ListDocumentPoliciesResponseResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListDocumentPoliciesResponseResponse]],
        Callable[[], Awaitable[Optional[ListDocumentPoliciesResponseResponse]]],
    ]

    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    headers: Dict[str, List[str]]

    list_document_policies_response: Optional[ListDocumentPoliciesResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ListDocumentPoliciesResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
