"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .factify_api_v1beta_organizationinvitestatus import (
    FactifyAPIV1betaOrganizationInviteStatus,
)
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ListOrganizationInvitesSecondsTypedDict = TypeAliasType(
    "ListOrganizationInvitesSecondsTypedDict", Union[int, str]
)
r"""Represents seconds of UTC time since Unix epoch
1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
9999-12-31T23:59:59Z inclusive.
"""


ListOrganizationInvitesSeconds = TypeAliasType(
    "ListOrganizationInvitesSeconds", Union[int, str]
)
r"""Represents seconds of UTC time since Unix epoch
1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
9999-12-31T23:59:59Z inclusive.
"""


class ListOrganizationInvitesRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization to list invitations for.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """
    status: NotRequired[List[FactifyAPIV1betaOrganizationInviteStatus]]
    r"""Filter by status. If empty, returns all invitations.
    ORGANIZATION_INVITE_STATUS_UNSPECIFIED (0) is not a valid filter value.
    """
    page_token: NotRequired[str]
    r"""Opaque pagination token from a previous response."""
    page_size: NotRequired[int]
    r"""Maximum number of items to return per page (1-100). Default: 50."""
    email_contains: NotRequired[str]
    r"""Case-insensitive substring match.
    REST: ?field.contains=value
    """
    email_exact: NotRequired[str]
    r"""Exact match (case-sensitive).
    REST: ?field.exact=value
    """
    sender_id: NotRequired[str]
    r"""Filter by sender. Only returns invitations sent by this user.
    REST: ?sender_id=user_01h2xcejqtf2nbrexx3vqjhp41
    Pattern: user_[0-9a-hjkmnp-tv-z]{26}
    """
    created_after_seconds: NotRequired[ListOrganizationInvitesSecondsTypedDict]
    r"""Represents seconds of UTC time since Unix epoch
    1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    9999-12-31T23:59:59Z inclusive.
    """
    created_after_nanos: NotRequired[int]
    r"""Non-negative fractions of a second at nanosecond resolution. Negative
    second values with fractions must still have non-negative nanos values
    that count forward in time. Must be from 0 to 999,999,999
    inclusive.
    """


class ListOrganizationInvitesRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Organization to list invitations for.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """

    status: Annotated[
        Optional[List[FactifyAPIV1betaOrganizationInviteStatus]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by status. If empty, returns all invitations.
    ORGANIZATION_INVITE_STATUS_UNSPECIFIED (0) is not a valid filter value.
    """

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination token from a previous response."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return per page (1-100). Default: 50."""

    email_contains: Annotated[
        Optional[str],
        pydantic.Field(alias="email.contains"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Case-insensitive substring match.
    REST: ?field.contains=value
    """

    email_exact: Annotated[
        Optional[str],
        pydantic.Field(alias="email.exact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Exact match (case-sensitive).
    REST: ?field.exact=value
    """

    sender_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by sender. Only returns invitations sent by this user.
    REST: ?sender_id=user_01h2xcejqtf2nbrexx3vqjhp41
    Pattern: user_[0-9a-hjkmnp-tv-z]{26}
    """

    created_after_seconds: Annotated[
        Optional[ListOrganizationInvitesSeconds],
        pydantic.Field(alias="created.after.seconds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Represents seconds of UTC time since Unix epoch
    1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    9999-12-31T23:59:59Z inclusive.
    """

    created_after_nanos: Annotated[
        Optional[int],
        pydantic.Field(alias="created.after.nanos"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Non-negative fractions of a second at nanosecond resolution. Negative
    second values with fractions must still have non-negative nanos values
    that count forward in time. Must be from 0 to 999,999,999
    inclusive.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "status",
                "page_token",
                "page_size",
                "email.contains",
                "email.exact",
                "sender_id",
                "created.after.seconds",
                "created.after.nanos",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
