"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listdocumentaccessresponse import (
    ListDocumentAccessResponse,
    ListDocumentAccessResponseTypedDict,
)
from factify.types import BaseModel
from factify.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class ListDocumentAccessRequestTypedDict(TypedDict):
    document_id: str
    r"""Document ID."""


class ListDocumentAccessRequest(BaseModel):
    document_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Document ID."""


class ListDocumentAccessResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListDocumentAccessResponseTypedDict


class ListDocumentAccessResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ListDocumentAccessResponse
