"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listorganizationsresponse import (
    ListOrganizationsResponse,
    ListOrganizationsResponseTypedDict,
)
from .organizationrole import OrganizationRole
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ListOrganizationsRequestTypedDict(TypedDict):
    page_token: NotRequired[str]
    r"""Opaque pagination token from a previous response."""
    page_size: NotRequired[int]
    r"""Maximum number of items to return per page (1-100). Default: 50."""
    role: NotRequired[List[OrganizationRole]]
    r"""Filter by the caller's role in the organization.
    If omitted or empty, returns all organizations the caller can view (no filtering).
    REST: ?role=admin or ?role=admin&role=owner
    """


class ListOrganizationsRequest(BaseModel):
    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination token from a previous response."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return per page (1-100). Default: 50."""

    role: Annotated[
        Optional[List[OrganizationRole]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by the caller's role in the organization.
    If omitted or empty, returns all organizations the caller can view (no filtering).
    REST: ?role=admin or ?role=admin&role=owner
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page_token", "page_size", "role"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListOrganizationsResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListOrganizationsResponseTypedDict


class ListOrganizationsResponseResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListOrganizationsResponseResponse]],
        Callable[[], Awaitable[Optional[ListOrganizationsResponseResponse]]],
    ]

    headers: Dict[str, List[str]]

    result: ListOrganizationsResponse
