"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apikeyquota import APIKeyQuota, APIKeyQuotaTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListAPIKeyQuotasResponseTypedDict(TypedDict):
    r"""ListAPIKeyQuotasResponse returns all key-level quotas."""

    quotas: NotRequired[List[APIKeyQuotaTypedDict]]
    r"""Per-key quota configurations and usage."""


class ListAPIKeyQuotasResponse(BaseModel):
    r"""ListAPIKeyQuotasResponse returns all key-level quotas."""

    quotas: Optional[List[APIKeyQuota]] = None
    r"""Per-key quota configurations and usage."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["quotas"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
