"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, UNSET_SENTINEL
from factify.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ListDocumentsSecondsTypedDict = TypeAliasType(
    "ListDocumentsSecondsTypedDict", Union[int, str]
)
r"""Represents seconds of UTC time since Unix epoch
1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
9999-12-31T23:59:59Z inclusive.
"""


ListDocumentsSeconds = TypeAliasType("ListDocumentsSeconds", Union[int, str])
r"""Represents seconds of UTC time since Unix epoch
1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
9999-12-31T23:59:59Z inclusive.
"""


class ListDocumentsRequestTypedDict(TypedDict):
    page_token: NotRequired[str]
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """
    page_size: NotRequired[int]
    r"""Maximum number of items to return per page (1-100). Default: 50."""
    created_after_seconds: NotRequired[ListDocumentsSecondsTypedDict]
    r"""Represents seconds of UTC time since Unix epoch
    1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    9999-12-31T23:59:59Z inclusive.
    """
    created_after_nanos: NotRequired[int]
    r"""Non-negative fractions of a second at nanosecond resolution. Negative
    second values with fractions must still have non-negative nanos values
    that count forward in time. Must be from 0 to 999,999,999
    inclusive.
    """
    created_by_id: NotRequired[str]
    r"""Filter by creator ID(s) (user or service account). Returns documents matching ANY of the specified IDs.
    Accepts single value or comma-separated list.
    REST: ?created_by_id=user_01h2xcejqtf2nbrexx3vqjhp41 or ?created_by_id=user_xxx,svc_yyy
    """
    access_level: NotRequired[str]
    r"""Filter by access level(s). Returns documents matching ANY of the specified levels.
    Accepts single value or comma-separated list.
    REST: ?access_level=private or ?access_level=private,organization
    Accepts clean enum names (case-insensitive): \"private\", \"organization\", \"public\" 
    """
    processing_status: NotRequired[str]
    r"""Filter by processing status(es). Returns documents matching ANY of the specified statuses.
    Accepts single value or comma-separated list.
    REST: ?processing_status=ready or ?processing_status=processing,ready,failed
    Accepts clean enum names (case-insensitive): \"processing\", \"ready\", \"failed\" 
    """


class ListDocumentsRequest(BaseModel):
    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque pagination token from a previous response.
    Pass next_page_token or prev_page_token from a previous response to continue pagination.
    Empty or omitted for the first page.
    """

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Maximum number of items to return per page (1-100). Default: 50."""

    created_after_seconds: Annotated[
        Optional[ListDocumentsSeconds],
        pydantic.Field(alias="created.after.seconds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Represents seconds of UTC time since Unix epoch
    1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    9999-12-31T23:59:59Z inclusive.
    """

    created_after_nanos: Annotated[
        Optional[int],
        pydantic.Field(alias="created.after.nanos"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Non-negative fractions of a second at nanosecond resolution. Negative
    second values with fractions must still have non-negative nanos values
    that count forward in time. Must be from 0 to 999,999,999
    inclusive.
    """

    created_by_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by creator ID(s) (user or service account). Returns documents matching ANY of the specified IDs.
    Accepts single value or comma-separated list.
    REST: ?created_by_id=user_01h2xcejqtf2nbrexx3vqjhp41 or ?created_by_id=user_xxx,svc_yyy
    """

    access_level: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by access level(s). Returns documents matching ANY of the specified levels.
    Accepts single value or comma-separated list.
    REST: ?access_level=private or ?access_level=private,organization
    Accepts clean enum names (case-insensitive): \"private\", \"organization\", \"public\" 
    """

    processing_status: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by processing status(es). Returns documents matching ANY of the specified statuses.
    Accepts single value or comma-separated list.
    REST: ?processing_status=ready or ?processing_status=processing,ready,failed
    Accepts clean enum names (case-insensitive): \"processing\", \"ready\", \"failed\" 
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "page_token",
                "page_size",
                "created.after.seconds",
                "created.after.nanos",
                "created_by_id",
                "access_level",
                "processing_status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
