"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from factify.types import BaseModel
from typing_extensions import TypedDict


class OrganizationTypedDict(TypedDict):
    r"""Organization represents a Factify organization."""

    created_at: datetime
    r"""Timestamp when the organization was created."""
    id: str
    r"""Unique ID for the organization.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """
    name: str
    r"""Human-readable organization name."""


class Organization(BaseModel):
    r"""Organization represents a Factify organization."""

    created_at: datetime
    r"""Timestamp when the organization was created."""

    id: str
    r"""Unique ID for the organization.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """

    name: str
    r"""Human-readable organization name."""
