"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_pathsegment import (
    QcrV1alphaPathSegment,
    QcrV1alphaPathSegmentTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaBlockPathTypedDict(TypedDict):
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    segments: NotRequired[List[QcrV1alphaPathSegmentTypedDict]]


class QcrV1alphaBlockPath(BaseModel):
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    segments: Optional[List[QcrV1alphaPathSegment]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["segments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
