"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaOrientation = Literal[
    "ORIENTATION_UNSPECIFIED",
    "ORIENTATION_PORTRAIT",
    "ORIENTATION_LANDSCAPE",
]
