"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_datacell import QcrV1alphaDataCell, QcrV1alphaDataCellTypedDict
from .value import Value, ValueTypedDict
from factify.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaDataRowTypedDict(TypedDict):
    r"""DataRow is a single record in a DataTable.
    cells are positional: cells[i] corresponds to columns[i].
    """

    attributes: NotRequired[Dict[str, Nullable[ValueTypedDict]]]
    r"""`Struct` represents a structured data value, consisting of fields
    which map to dynamically typed values. In some languages, `Struct`
    might be supported by a native representation. For example, in
    scripting languages like JS a struct is represented as an
    object. The details of that representation are described together
    with the proto support for the language.

    The JSON representation for `Struct` is JSON object.
    """
    cells: NotRequired[List[QcrV1alphaDataCellTypedDict]]


class QcrV1alphaDataRow(BaseModel):
    r"""DataRow is a single record in a DataTable.
    cells are positional: cells[i] corresponds to columns[i].
    """

    attributes: Optional[Dict[str, Nullable[Value]]] = None
    r"""`Struct` represents a structured data value, consisting of fields
    which map to dynamically typed values. In some languages, `Struct`
    might be supported by a native representation. For example, in
    scripting languages like JS a struct is represented as an
    object. The details of that representation are described together
    with the proto support for the language.

    The JSON representation for `Struct` is JSON object.
    """

    cells: Optional[List[QcrV1alphaDataCell]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes", "cells"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
