"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_linespacingvalue import (
    QcrV1alphaLineSpacingValue,
    QcrV1alphaLineSpacingValueTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaBlockSpacingTypedDict(TypedDict):
    after_mm: NotRequired[float]
    before_mm: NotRequired[float]
    line_spacing: NotRequired[QcrV1alphaLineSpacingValueTypedDict]
    r"""Line spacing as mode + optional explicit value.
    Using a message instead of a bare enum avoids a future wire break when
    exact/at-least modes are added (they need a companion float value).
    """


class QcrV1alphaBlockSpacing(BaseModel):
    after_mm: Optional[float] = None

    before_mm: Optional[float] = None

    line_spacing: Optional[QcrV1alphaLineSpacingValue] = None
    r"""Line spacing as mode + optional explicit value.
    Using a message instead of a bare enum avoids a future wire break when
    exact/at-least modes are added (they need a companion float value).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["after_mm", "before_mm", "line_spacing"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
