"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaCellErrorType = Literal[
    "CELL_ERROR_TYPE_UNSPECIFIED",
    "CELL_ERROR_TYPE_NULL",
    "CELL_ERROR_TYPE_DIV_ZERO",
    "CELL_ERROR_TYPE_VALUE",
    "CELL_ERROR_TYPE_REF",
    "CELL_ERROR_TYPE_NAME",
    "CELL_ERROR_TYPE_NUM",
    "CELL_ERROR_TYPE_NA",
    "CELL_ERROR_TYPE_GETTING_DATA",
    "CELL_ERROR_TYPE_SPILL",
    "CELL_ERROR_TYPE_CALC",
]
