"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_block import QcrV1alphaBlock, QcrV1alphaBlockTypedDict
from .qcr_v1alpha_documentmetadata import (
    QcrV1alphaDocumentMetadata,
    QcrV1alphaDocumentMetadataTypedDict,
)
from .qcr_v1alpha_sourcereference import (
    QcrV1alphaSourceReference,
    QcrV1alphaSourceReferenceTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaDocumentRecordTypedDict(TypedDict):
    r"""DocumentRecord is the QCR representation of an ingested document.
    Immutable once extracted. Source-format-agnostic.

    Structure is a flat sequence of blocks. Sections provide optional grouping
    and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
    — they do not contain other blocks. This constrains nesting to only what is
    semantically valid and gives every element a natural positional address.

    Addressing convention: every element is addressable by its index path through
    the typed containment hierarchy. Examples:
    blocks[2]                        → third block
    blocks[2].section.blocks[0]      → first block inside a section
    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
    blocks[3].list.items[2]          → third item of a list

    These addresses are deterministic for a given record and are used by
    DocumentLayout to join layout data to semantic content.
    """

    blocks: NotRequired[List[QcrV1alphaBlockTypedDict]]
    id: NotRequired[str]
    metadata: NotRequired[QcrV1alphaDocumentMetadataTypedDict]
    source: NotRequired[QcrV1alphaSourceReferenceTypedDict]
    r"""SourceReference links a record back to the source it was extracted from.

    Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
    format, content hash, storage location, checksums, external URLs — goes
    in the attributes bag, because the relevant metadata varies by source type.

    Examples by source type:

    File upload:
    source_id  = \"intg_01j8k...\"                    (upload channel instance)
    remote_id  = \"req_01h2xcejqtf2nbrexx3vqjhp41\"   (upload request ID)
    attributes = {format: \"pdf\", location: \"uploads/.../original.pdf\",
    content_hash: \"a1b2c3...\", storage_etag: \"\\"abc\\"\"}

    Gmail integration:
    source_id  = \"intg_01k9m...\"                    (Gmail connector instance)
    remote_id  = \"18abc123def\"                       (Gmail message ID)
    attributes = {format: \"eml\", thread_id: \"...\",
    external_url: \"https://mail.google.com/...\"}

    Confluence sync:
    source_id  = \"intg_01p3q...\"                    (Confluence connector instance)
    remote_id  = \"12345678\"                          (Confluence page ID)
    attributes = {format: \"html\", space_key: \"ENG\",
    external_url: \"https://acme.atlassian.net/wiki/...\"}
    """


class QcrV1alphaDocumentRecord(BaseModel):
    r"""DocumentRecord is the QCR representation of an ingested document.
    Immutable once extracted. Source-format-agnostic.

    Structure is a flat sequence of blocks. Sections provide optional grouping
    and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
    — they do not contain other blocks. This constrains nesting to only what is
    semantically valid and gives every element a natural positional address.

    Addressing convention: every element is addressable by its index path through
    the typed containment hierarchy. Examples:
    blocks[2]                        → third block
    blocks[2].section.blocks[0]      → first block inside a section
    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
    blocks[3].list.items[2]          → third item of a list

    These addresses are deterministic for a given record and are used by
    DocumentLayout to join layout data to semantic content.
    """

    blocks: Optional[List[QcrV1alphaBlock]] = None

    id: Optional[str] = None

    metadata: Optional[QcrV1alphaDocumentMetadata] = None

    source: Optional[QcrV1alphaSourceReference] = None
    r"""SourceReference links a record back to the source it was extracted from.

    Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
    format, content hash, storage location, checksums, external URLs — goes
    in the attributes bag, because the relevant metadata varies by source type.

    Examples by source type:

    File upload:
    source_id  = \"intg_01j8k...\"                    (upload channel instance)
    remote_id  = \"req_01h2xcejqtf2nbrexx3vqjhp41\"   (upload request ID)
    attributes = {format: \"pdf\", location: \"uploads/.../original.pdf\",
    content_hash: \"a1b2c3...\", storage_etag: \"\\"abc\\"\"}

    Gmail integration:
    source_id  = \"intg_01k9m...\"                    (Gmail connector instance)
    remote_id  = \"18abc123def\"                       (Gmail message ID)
    attributes = {format: \"eml\", thread_id: \"...\",
    external_url: \"https://mail.google.com/...\"}

    Confluence sync:
    source_id  = \"intg_01p3q...\"                    (Confluence connector instance)
    remote_id  = \"12345678\"                          (Confluence page ID)
    attributes = {format: \"html\", space_key: \"ENG\",
    external_url: \"https://acme.atlassian.net/wiki/...\"}
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["blocks", "id", "metadata", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
