"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel
from typing import Union
from typing_extensions import TypeAliasType, TypedDict


class RowTypedDict(TypedDict):
    row: int
    r"""index into TableData.rows[]"""


class Row(BaseModel):
    row: int
    r"""index into TableData.rows[]"""


class ItemTypedDict(TypedDict):
    item: int
    r"""index into ListData.items[] or sub_list.items[]"""


class Item(BaseModel):
    item: int
    r"""index into ListData.items[] or sub_list.items[]"""


class CellTypedDict(TypedDict):
    cell: int
    r"""index into Row.cells[]"""


class Cell(BaseModel):
    cell: int
    r"""index into Row.cells[]"""


class BlockTypedDict(TypedDict):
    block: int
    r"""index into blocks[] (document-level or section-level)"""


class Block(BaseModel):
    block: int
    r"""index into blocks[] (document-level or section-level)"""


QcrV1alphaPathSegmentTypedDict = TypeAliasType(
    "QcrV1alphaPathSegmentTypedDict",
    Union[BlockTypedDict, CellTypedDict, ItemTypedDict, RowTypedDict],
)


QcrV1alphaPathSegment = TypeAliasType(
    "QcrV1alphaPathSegment", Union[Block, Cell, Item, Row]
)
