"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaTableWidthMode = Literal[
    "TABLE_WIDTH_MODE_UNSPECIFIED",
    "TABLE_WIDTH_MODE_AUTO",
    "TABLE_WIDTH_MODE_FIXED",
]
