"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_blockspacing import (
    QcrV1alphaBlockSpacing,
    QcrV1alphaBlockSpacingTypedDict,
)
from .qcr_v1alpha_indentation import (
    QcrV1alphaIndentation,
    QcrV1alphaIndentationTypedDict,
)
from .qcr_v1alpha_textalignment import QcrV1alphaTextAlignment
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaTextBlockLayoutTypedDict(TypedDict):
    r"""Layout for block-level text elements (paragraphs, headings, list items, quotes)."""

    alignment: NotRequired[QcrV1alphaTextAlignment]
    indentation: NotRequired[QcrV1alphaIndentationTypedDict]
    spacing: NotRequired[QcrV1alphaBlockSpacingTypedDict]


class QcrV1alphaTextBlockLayout(BaseModel):
    r"""Layout for block-level text elements (paragraphs, headings, list items, quotes)."""

    alignment: Optional[QcrV1alphaTextAlignment] = None

    indentation: Optional[QcrV1alphaIndentation] = None

    spacing: Optional[QcrV1alphaBlockSpacing] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alignment", "indentation", "spacing"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
