"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaBoundingBoxTypedDict(TypedDict):
    r"""Normalized bounding box relative to the page (0.0–1.0).
    Origin is top-left: (0,0) is the top-left corner of the page,
    x increases rightward, y increases downward.
    Extraction pipelines must flip the y-axis for bottom-left origin formats (PDF).
    To get absolute coordinates, multiply by the page's PhysicalDimensions.
    """

    height: NotRequired[float]
    width: NotRequired[float]
    x: NotRequired[float]
    y: NotRequired[float]


class QcrV1alphaBoundingBox(BaseModel):
    r"""Normalized bounding box relative to the page (0.0–1.0).
    Origin is top-left: (0,0) is the top-left corner of the page,
    x increases rightward, y increases downward.
    Extraction pipelines must flip the y-axis for bottom-left origin formats (PDF).
    To get absolute coordinates, multiply by the page's PhysicalDimensions.
    """

    height: Optional[float] = None

    width: Optional[float] = None

    x: Optional[float] = None

    y: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["height", "width", "x", "y"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
