"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaPageSize = Literal[
    "PAGE_SIZE_UNSPECIFIED",
    "PAGE_SIZE_A4",
    "PAGE_SIZE_LETTER",
    "PAGE_SIZE_LEGAL",
    "PAGE_SIZE_A3",
    "PAGE_SIZE_TABLOID",
    "PAGE_SIZE_CUSTOM",
]
