"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_namedrange import QcrV1alphaNamedRange, QcrV1alphaNamedRangeTypedDict
from .qcr_v1alpha_sheet import QcrV1alphaSheet, QcrV1alphaSheetTypedDict
from .qcr_v1alpha_sourcereference import (
    QcrV1alphaSourceReference,
    QcrV1alphaSourceReferenceTypedDict,
)
from .qcr_v1alpha_spreadsheetmetadata import (
    QcrV1alphaSpreadsheetMetadata,
    QcrV1alphaSpreadsheetMetadataTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaSpreadsheetRecordTypedDict(TypedDict):
    r"""SpreadsheetRecord is the QCR representation of an ingested spreadsheet
    workbook (XLSX, CSV, Parquet). Immutable once extracted. Source-format-agnostic.

    Hierarchy: SpreadsheetRecord 1:M Sheet 1:M DataTable/SheetImage/SheetChart.
    The semantic core is DataTable: named, typed columns applied to ordered rows.
    The extractor identifies headers and schemas so consumers don't have to.
    """

    id: NotRequired[str]
    metadata: NotRequired[QcrV1alphaSpreadsheetMetadataTypedDict]
    named_ranges: NotRequired[List[QcrV1alphaNamedRangeTypedDict]]
    sheets: NotRequired[List[QcrV1alphaSheetTypedDict]]
    source: NotRequired[QcrV1alphaSourceReferenceTypedDict]
    r"""SourceReference links a record back to the source it was extracted from.

    Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
    format, content hash, storage location, checksums, external URLs — goes
    in the attributes bag, because the relevant metadata varies by source type.

    Examples by source type:

    File upload:
    source_id  = \"intg_01j8k...\"                    (upload channel instance)
    remote_id  = \"req_01h2xcejqtf2nbrexx3vqjhp41\"   (upload request ID)
    attributes = {format: \"pdf\", location: \"uploads/.../original.pdf\",
    content_hash: \"a1b2c3...\", storage_etag: \"\\"abc\\"\"}

    Gmail integration:
    source_id  = \"intg_01k9m...\"                    (Gmail connector instance)
    remote_id  = \"18abc123def\"                       (Gmail message ID)
    attributes = {format: \"eml\", thread_id: \"...\",
    external_url: \"https://mail.google.com/...\"}

    Confluence sync:
    source_id  = \"intg_01p3q...\"                    (Confluence connector instance)
    remote_id  = \"12345678\"                          (Confluence page ID)
    attributes = {format: \"html\", space_key: \"ENG\",
    external_url: \"https://acme.atlassian.net/wiki/...\"}
    """


class QcrV1alphaSpreadsheetRecord(BaseModel):
    r"""SpreadsheetRecord is the QCR representation of an ingested spreadsheet
    workbook (XLSX, CSV, Parquet). Immutable once extracted. Source-format-agnostic.

    Hierarchy: SpreadsheetRecord 1:M Sheet 1:M DataTable/SheetImage/SheetChart.
    The semantic core is DataTable: named, typed columns applied to ordered rows.
    The extractor identifies headers and schemas so consumers don't have to.
    """

    id: Optional[str] = None

    metadata: Optional[QcrV1alphaSpreadsheetMetadata] = None

    named_ranges: Optional[List[QcrV1alphaNamedRange]] = None

    sheets: Optional[List[QcrV1alphaSheet]] = None

    source: Optional[QcrV1alphaSourceReference] = None
    r"""SourceReference links a record back to the source it was extracted from.

    Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
    format, content hash, storage location, checksums, external URLs — goes
    in the attributes bag, because the relevant metadata varies by source type.

    Examples by source type:

    File upload:
    source_id  = \"intg_01j8k...\"                    (upload channel instance)
    remote_id  = \"req_01h2xcejqtf2nbrexx3vqjhp41\"   (upload request ID)
    attributes = {format: \"pdf\", location: \"uploads/.../original.pdf\",
    content_hash: \"a1b2c3...\", storage_etag: \"\\"abc\\"\"}

    Gmail integration:
    source_id  = \"intg_01k9m...\"                    (Gmail connector instance)
    remote_id  = \"18abc123def\"                       (Gmail message ID)
    attributes = {format: \"eml\", thread_id: \"...\",
    external_url: \"https://mail.google.com/...\"}

    Confluence sync:
    source_id  = \"intg_01p3q...\"                    (Confluence connector instance)
    remote_id  = \"12345678\"                          (Confluence page ID)
    attributes = {format: \"html\", space_key: \"ENG\",
    external_url: \"https://acme.atlassian.net/wiki/...\"}
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "metadata", "named_ranges", "sheets", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
