"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_celllayoutbinding import (
    QcrV1alphaCellLayoutBinding,
    QcrV1alphaCellLayoutBindingTypedDict,
)
from .qcr_v1alpha_columnformatbinding import (
    QcrV1alphaColumnFormatBinding,
    QcrV1alphaColumnFormatBindingTypedDict,
)
from .qcr_v1alpha_columnlayout import (
    QcrV1alphaColumnLayout,
    QcrV1alphaColumnLayoutTypedDict,
)
from .qcr_v1alpha_direction import QcrV1alphaDirection
from .qcr_v1alpha_frozenpane import QcrV1alphaFrozenPane, QcrV1alphaFrozenPaneTypedDict
from .qcr_v1alpha_mergedregion import (
    QcrV1alphaMergedRegion,
    QcrV1alphaMergedRegionTypedDict,
)
from .qcr_v1alpha_rowlayout import QcrV1alphaRowLayout, QcrV1alphaRowLayoutTypedDict
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaSheetLayoutTypedDict(TypedDict):
    cell_bindings: NotRequired[List[QcrV1alphaCellLayoutBindingTypedDict]]
    column_formats: NotRequired[List[QcrV1alphaColumnFormatBindingTypedDict]]
    columns: NotRequired[List[QcrV1alphaColumnLayoutTypedDict]]
    direction: NotRequired[QcrV1alphaDirection]
    r"""Text direction / reading order."""
    frozen_pane: NotRequired[QcrV1alphaFrozenPaneTypedDict]
    is_hidden: NotRequired[bool]
    merged_regions: NotRequired[List[QcrV1alphaMergedRegionTypedDict]]
    rows: NotRequired[List[QcrV1alphaRowLayoutTypedDict]]
    sheet_name: NotRequired[str]
    r"""references Sheet.name"""


class QcrV1alphaSheetLayout(BaseModel):
    cell_bindings: Optional[List[QcrV1alphaCellLayoutBinding]] = None

    column_formats: Optional[List[QcrV1alphaColumnFormatBinding]] = None

    columns: Optional[List[QcrV1alphaColumnLayout]] = None

    direction: Optional[QcrV1alphaDirection] = None
    r"""Text direction / reading order."""

    frozen_pane: Optional[QcrV1alphaFrozenPane] = None

    is_hidden: Optional[bool] = None

    merged_regions: Optional[List[QcrV1alphaMergedRegion]] = None

    rows: Optional[List[QcrV1alphaRowLayout]] = None

    sheet_name: Optional[str] = None
    r"""references Sheet.name"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cell_bindings",
                "column_formats",
                "columns",
                "direction",
                "frozen_pane",
                "is_hidden",
                "merged_regions",
                "rows",
                "sheet_name",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
