"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel
from typing_extensions import TypedDict


class QcrV1alphaThematicBreakDataTypedDict(TypedDict):
    r"""Explicit authorial boundary (e.g. markdown `---`). Leaf block, no children."""


class QcrV1alphaThematicBreakData(BaseModel):
    r"""Explicit authorial boundary (e.g. markdown `---`). Leaf block, no children."""
