"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_blockpath import QcrV1alphaBlockPath, QcrV1alphaBlockPathTypedDict
from .qcr_v1alpha_layoutfragment import (
    QcrV1alphaLayoutFragment,
    QcrV1alphaLayoutFragmentTypedDict,
)
from .qcr_v1alpha_tablecelllayout import (
    QcrV1alphaTableCellLayout,
    QcrV1alphaTableCellLayoutTypedDict,
)
from .qcr_v1alpha_tablelayout import (
    QcrV1alphaTableLayout,
    QcrV1alphaTableLayoutTypedDict,
)
from .qcr_v1alpha_tablerowlayout import (
    QcrV1alphaTableRowLayout,
    QcrV1alphaTableRowLayoutTypedDict,
)
from .qcr_v1alpha_textblocklayout import (
    QcrV1alphaTextBlockLayout,
    QcrV1alphaTextBlockLayoutTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class TextBlockTypedDict(TypedDict):
    text_block: QcrV1alphaTextBlockLayoutTypedDict
    r"""Layout for block-level text elements (paragraphs, headings, list items, quotes)."""
    fragments: NotRequired[List[QcrV1alphaLayoutFragmentTypedDict]]
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """
    path: NotRequired[QcrV1alphaBlockPathTypedDict]
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """


class TextBlock(BaseModel):
    text_block: QcrV1alphaTextBlockLayout
    r"""Layout for block-level text elements (paragraphs, headings, list items, quotes)."""

    fragments: Optional[List[QcrV1alphaLayoutFragment]] = None
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """

    path: Optional[QcrV1alphaBlockPath] = None
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fragments", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TableRowTypedDict(TypedDict):
    table_row: QcrV1alphaTableRowLayoutTypedDict
    fragments: NotRequired[List[QcrV1alphaLayoutFragmentTypedDict]]
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """
    path: NotRequired[QcrV1alphaBlockPathTypedDict]
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """


class TableRow(BaseModel):
    table_row: QcrV1alphaTableRowLayout

    fragments: Optional[List[QcrV1alphaLayoutFragment]] = None
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """

    path: Optional[QcrV1alphaBlockPath] = None
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fragments", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TableCellTypedDict(TypedDict):
    table_cell: QcrV1alphaTableCellLayoutTypedDict
    fragments: NotRequired[List[QcrV1alphaLayoutFragmentTypedDict]]
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """
    path: NotRequired[QcrV1alphaBlockPathTypedDict]
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """


class TableCell(BaseModel):
    table_cell: QcrV1alphaTableCellLayout

    fragments: Optional[List[QcrV1alphaLayoutFragment]] = None
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """

    path: Optional[QcrV1alphaBlockPath] = None
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fragments", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QcrV1alphaLayoutBindingTableTypedDict(TypedDict):
    table: QcrV1alphaTableLayoutTypedDict
    fragments: NotRequired[List[QcrV1alphaLayoutFragmentTypedDict]]
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """
    path: NotRequired[QcrV1alphaBlockPathTypedDict]
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """


class QcrV1alphaLayoutBindingTable(BaseModel):
    table: QcrV1alphaTableLayout

    fragments: Optional[List[QcrV1alphaLayoutFragment]] = None
    r"""Spatial fragments — one per page the element appears on.
    A paragraph spanning pages 3–4 has two fragments.
    Order matches reading order (fragment 0 is the first appearance).
    """

    path: Optional[QcrV1alphaBlockPath] = None
    r"""BlockPath addresses an element within the record's typed containment
    hierarchy. Each segment steps into a specific typed child collection.

    Examples:
    [block(2)]                                → blocks[2]
    [block(2), block(0)]                      → blocks[2].section.blocks[0]
    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
    [block(3), item(2)]                       → blocks[3].list.items[2]
    [block(3), item(2), item(0)]              → nested sub-list item

    The path is unambiguous because each segment type implies which child
    collection to descend into (blocks for sections, rows for tables, etc.).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fragments", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


QcrV1alphaLayoutBindingTypedDict = TypeAliasType(
    "QcrV1alphaLayoutBindingTypedDict",
    Union[
        QcrV1alphaLayoutBindingTableTypedDict,
        TableCellTypedDict,
        TableRowTypedDict,
        TextBlockTypedDict,
    ],
)
r"""LayoutBinding attaches layout data to a specific element in the record.
One binding per addressable element. Elements without layout data have no
binding entry (sparse).
"""


QcrV1alphaLayoutBinding = TypeAliasType(
    "QcrV1alphaLayoutBinding",
    Union[QcrV1alphaLayoutBindingTable, TableCell, TableRow, TextBlock],
)
r"""LayoutBinding attaches layout data to a specific element in the record.
One binding per addressable element. Elements without layout data have no
binding entry (sparse).
"""
