"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaLineSpacing = Literal[
    "LINE_SPACING_UNSPECIFIED",
    "LINE_SPACING_SINGLE",
    "LINE_SPACING_ONE_AND_HALF",
    "LINE_SPACING_DOUBLE",
]
