"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_datatable import QcrV1alphaDataTable, QcrV1alphaDataTableTypedDict
from .qcr_v1alpha_sheetchart import QcrV1alphaSheetChart, QcrV1alphaSheetChartTypedDict
from .qcr_v1alpha_sheetimage import QcrV1alphaSheetImage, QcrV1alphaSheetImageTypedDict
from .value import Value, ValueTypedDict
from factify.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaSheetTypedDict(TypedDict):
    attributes: NotRequired[Dict[str, Nullable[ValueTypedDict]]]
    r"""`Struct` represents a structured data value, consisting of fields
    which map to dynamically typed values. In some languages, `Struct`
    might be supported by a native representation. For example, in
    scripting languages like JS a struct is represented as an
    object. The details of that representation are described together
    with the proto support for the language.

    The JSON representation for `Struct` is JSON object.
    """
    charts: NotRequired[List[QcrV1alphaSheetChartTypedDict]]
    images: NotRequired[List[QcrV1alphaSheetImageTypedDict]]
    name: NotRequired[str]
    r"""unique within workbook, used as join key by SheetLayout"""
    tables: NotRequired[List[QcrV1alphaDataTableTypedDict]]


class QcrV1alphaSheet(BaseModel):
    attributes: Optional[Dict[str, Nullable[Value]]] = None
    r"""`Struct` represents a structured data value, consisting of fields
    which map to dynamically typed values. In some languages, `Struct`
    might be supported by a native representation. For example, in
    scripting languages like JS a struct is represented as an
    object. The details of that representation are described together
    with the proto support for the language.

    The JSON representation for `Struct` is JSON object.
    """

    charts: Optional[List[QcrV1alphaSheetChart]] = None

    images: Optional[List[QcrV1alphaSheetImage]] = None

    name: Optional[str] = None
    r"""unique within workbook, used as join key by SheetLayout"""

    tables: Optional[List[QcrV1alphaDataTable]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes", "charts", "images", "name", "tables"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
