"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .qcr_v1alpha_block import QcrV1alphaBlock, QcrV1alphaBlockTypedDict


class QcrV1alphaSectionDataTypedDict(TypedDict):
    r"""Section groups blocks under a logical heading. Only sections can nest blocks."""

    blocks: NotRequired[List["QcrV1alphaBlockTypedDict"]]


class QcrV1alphaSectionData(BaseModel):
    r"""Section groups blocks under a logical heading. Only sections can nest blocks."""

    blocks: Optional[List["QcrV1alphaBlock"]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["blocks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
