"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_direction import QcrV1alphaDirection
from .qcr_v1alpha_margins import QcrV1alphaMargins, QcrV1alphaMarginsTypedDict
from .qcr_v1alpha_orientation import QcrV1alphaOrientation
from .qcr_v1alpha_pagesize import QcrV1alphaPageSize
from .qcr_v1alpha_physicaldimensions import (
    QcrV1alphaPhysicalDimensions,
    QcrV1alphaPhysicalDimensionsTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaLayoutDefaultsTypedDict(TypedDict):
    r"""Document-wide layout defaults."""

    dimensions: NotRequired[QcrV1alphaPhysicalDimensionsTypedDict]
    r"""Physical dimensions in millimeters."""
    direction: NotRequired[QcrV1alphaDirection]
    r"""Text direction / reading order."""
    margins: NotRequired[QcrV1alphaMarginsTypedDict]
    r"""Page/section margins in millimeters."""
    orientation: NotRequired[QcrV1alphaOrientation]
    page_size: NotRequired[QcrV1alphaPageSize]


class QcrV1alphaLayoutDefaults(BaseModel):
    r"""Document-wide layout defaults."""

    dimensions: Optional[QcrV1alphaPhysicalDimensions] = None
    r"""Physical dimensions in millimeters."""

    direction: Optional[QcrV1alphaDirection] = None
    r"""Text direction / reading order."""

    margins: Optional[QcrV1alphaMargins] = None
    r"""Page/section margins in millimeters."""

    orientation: Optional[QcrV1alphaOrientation] = None

    page_size: Optional[QcrV1alphaPageSize] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["dimensions", "direction", "margins", "orientation", "page_size"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
