"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QcrV1alphaTextAlignment = Literal[
    "TEXT_ALIGNMENT_UNSPECIFIED",
    "TEXT_ALIGNMENT_LEFT",
    "TEXT_ALIGNMENT_CENTER",
    "TEXT_ALIGNMENT_RIGHT",
    "TEXT_ALIGNMENT_JUSTIFY",
]
