"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_tabledata_row_cell import (
    QcrV1alphaTableDataRowCell,
    QcrV1alphaTableDataRowCellTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QcrV1alphaTableDataRowTypedDict(TypedDict):
    cells: NotRequired[List[QcrV1alphaTableDataRowCellTypedDict]]


class QcrV1alphaTableDataRow(BaseModel):
    cells: Optional[List[QcrV1alphaTableDataRowCell]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cells"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
