"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


QuotaTier = Literal[
    "QUOTA_TIER_UNSPECIFIED",
    "QUOTA_TIER_FREE",
    "QUOTA_TIER_CUSTOM",
]
r"""QuotaTier represents the organization's quota tier."""
