"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .revokeorganizationinviteresponse import (
    RevokeOrganizationInviteResponse,
    RevokeOrganizationInviteResponseTypedDict,
)
from factify.types import BaseModel
from factify.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class RevokeOrganizationInviteRevokeOrganizationInviteRequestTypedDict(TypedDict):
    r"""RevokeOrganizationInviteRequest identifies an invitation to revoke."""


class RevokeOrganizationInviteRevokeOrganizationInviteRequest(BaseModel):
    r"""RevokeOrganizationInviteRequest identifies an invitation to revoke."""


class RevokeOrganizationInviteRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization the invitation belongs to.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """
    invite_id: str
    r"""Invitation ID to revoke.
    Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
    """
    body: RevokeOrganizationInviteRevokeOrganizationInviteRequestTypedDict


class RevokeOrganizationInviteRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Organization the invitation belongs to.
    Pattern: org_[0-9a-hjkmnp-tv-z]{26}
    """

    invite_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Invitation ID to revoke.
    Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
    """

    body: Annotated[
        RevokeOrganizationInviteRevokeOrganizationInviteRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class RevokeOrganizationInviteResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: RevokeOrganizationInviteResponseTypedDict


class RevokeOrganizationInviteResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: RevokeOrganizationInviteResponse
