"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .revokeapikeyresponse import RevokeAPIKeyResponse, RevokeAPIKeyResponseTypedDict
from factify.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Dict, List
from typing_extensions import Annotated, NotRequired, TypedDict


class RevokeAPIKeyRevokeAPIKeyRequestTypedDict(TypedDict):
    r"""RevokeApiKeyRequest identifies an API key to revoke."""

    reason: NotRequired[Nullable[str]]
    r"""Optional reason for revocation (for audit purposes).
    The revoking user's identity and timestamp are captured in audit logs separately.
    """


class RevokeAPIKeyRevokeAPIKeyRequest(BaseModel):
    r"""RevokeApiKeyRequest identifies an API key to revoke."""

    reason: OptionalNullable[str] = UNSET
    r"""Optional reason for revocation (for audit purposes).
    The revoking user's identity and timestamp are captured in audit logs separately.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reason"])
        nullable_fields = set(["reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class RevokeAPIKeyRequestTypedDict(TypedDict):
    api_key_id: str
    r"""API key ID to revoke.
    Pattern: key_[0-9a-hjkmnp-tv-z]{26}
    """
    body: RevokeAPIKeyRevokeAPIKeyRequestTypedDict


class RevokeAPIKeyRequest(BaseModel):
    api_key_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""API key ID to revoke.
    Pattern: key_[0-9a-hjkmnp-tv-z]{26}
    """

    body: Annotated[
        RevokeAPIKeyRevokeAPIKeyRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class RevokeAPIKeyResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: RevokeAPIKeyResponseTypedDict


class RevokeAPIKeyResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: RevokeAPIKeyResponse
