"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .qcr_v1alpha_spreadsheetlayout import (
    QcrV1alphaSpreadsheetLayout,
    QcrV1alphaSpreadsheetLayoutTypedDict,
)
from .qcr_v1alpha_spreadsheetrecord import (
    QcrV1alphaSpreadsheetRecord,
    QcrV1alphaSpreadsheetRecordTypedDict,
)
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SpreadsheetBundleTypedDict(TypedDict):
    r"""SpreadsheetBundle groups a spreadsheet record with its optional grid layout."""

    layout: NotRequired[QcrV1alphaSpreadsheetLayoutTypedDict]
    record: NotRequired[QcrV1alphaSpreadsheetRecordTypedDict]
    r"""SpreadsheetRecord is the QCR representation of an ingested spreadsheet
    workbook (XLSX, CSV, Parquet). Immutable once extracted. Source-format-agnostic.

    Hierarchy: SpreadsheetRecord 1:M Sheet 1:M DataTable/SheetImage/SheetChart.
    The semantic core is DataTable: named, typed columns applied to ordered rows.
    The extractor identifies headers and schemas so consumers don't have to.
    """


class SpreadsheetBundle(BaseModel):
    r"""SpreadsheetBundle groups a spreadsheet record with its optional grid layout."""

    layout: Optional[QcrV1alphaSpreadsheetLayout] = None

    record: Optional[QcrV1alphaSpreadsheetRecord] = None
    r"""SpreadsheetRecord is the QCR representation of an ingested spreadsheet
    workbook (XLSX, CSV, Parquet). Immutable once extracted. Source-format-agnostic.

    Hierarchy: SpreadsheetRecord 1:M Sheet 1:M DataTable/SheetImage/SheetChart.
    The semantic core is DataTable: named, typed columns applied to ordered rows.
    The extractor identifies headers and schemas so consumers don't have to.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["layout", "record"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
