"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from factify.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateVersionUpdateVersionRequestTypedDict(TypedDict):
    r"""UpdateVersionRequest specifies fields to update on a version."""

    version_id: NotRequired[str]
    r"""Version ID to update.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """
    title: NotRequired[Nullable[str]]
    r"""New title (max 255 characters)."""
    description: NotRequired[Nullable[str]]
    r"""New description."""


class UpdateVersionUpdateVersionRequest(BaseModel):
    r"""UpdateVersionRequest specifies fields to update on a version."""

    version_id: Optional[str] = None
    r"""Version ID to update.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """

    title: OptionalNullable[str] = UNSET
    r"""New title (max 255 characters)."""

    description: OptionalNullable[str] = UNSET
    r"""New description."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["version_id", "title", "description"])
        nullable_fields = set(["title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateVersionRequestTypedDict(TypedDict):
    version_id_param: str
    r"""Version ID to update.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """
    body: UpdateVersionUpdateVersionRequestTypedDict


class UpdateVersionRequest(BaseModel):
    version_id_param: Annotated[
        str,
        pydantic.Field(alias="version_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Version ID to update.
    Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
    """

    body: Annotated[
        UpdateVersionUpdateVersionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
