"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from factify.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateDocumentAccessResponseTypedDict(TypedDict):
    r"""UpdateDocumentAccessResponse contains the result of updating access."""

    error: NotRequired[str]
    r"""Error message if the update failed."""
    success: NotRequired[bool]
    r"""Whether the update succeeded."""


class UpdateDocumentAccessResponse(BaseModel):
    r"""UpdateDocumentAccessResponse contains the result of updating access."""

    error: Optional[str] = None
    r"""Error message if the update failed."""

    success: Optional[bool] = None
    r"""Whether the update succeeded."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error", "success"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
