"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usertype import UserType
from factify.types import BaseModel
from typing_extensions import TypedDict


class UserTypedDict(TypedDict):
    r"""User represents a user or service account."""

    id: str
    r"""Unique ID for the user or service account.
    Pattern: user_[0-9a-hjkmnp-tv-z]{26} for users, svc_[0-9a-hjkmnp-tv-z]{26} for service accounts
    """
    name: str
    r"""Display name of the user or service account."""
    type: UserType


class User(BaseModel):
    r"""User represents a user or service account."""

    id: str
    r"""Unique ID for the user or service account.
    Pattern: user_[0-9a-hjkmnp-tv-z]{26} for users, svc_[0-9a-hjkmnp-tv-z]{26} for service accounts
    """

    name: str
    r"""Display name of the user or service account."""

    type: UserType
