"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .factifyerror import FactifyError
from typing import TYPE_CHECKING

from factify.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .error import Error, ErrorData
    from .factifydefaulterror import FactifyDefaultError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "Error",
    "ErrorData",
    "FactifyDefaultError",
    "FactifyError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "Error": ".error",
    "ErrorData": ".error",
    "FactifyDefaultError": ".factifydefaulterror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> object:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
