"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from factify.errors import FactifyError
from factify.models import error as models_error, httpmetadata as models_httpmetadata
from factify.types import BaseModel
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated


class ErrorData(BaseModel):
    error: models_error.Error
    http_meta: Annotated[
        Optional[models_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None


@dataclass(unsafe_hash=True)
class Error(FactifyError):
    r"""Invalid request parameters"""

    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
